"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input, Select } from "@/components/ui/Input";
import { createClient } from "@/lib/supabase/client";
import { exportLocalData } from "@/lib/export-data";
import { isLocalMode } from "@/lib/local";
import { usePreferences } from "@/hooks/usePreferences";
import type { ThemePreference } from "@/types";

export default function AjustesPage() {
  const router = useRouter(); const prefs = usePreferences(); const modoLocal = prefs.local || isLocalMode();
  async function cerrarSesion() { document.cookie = "mi_despensa_local=; path=/; max-age=0; SameSite=Lax"; await createClient().auth.signOut(); router.push("/auth/login"); }
  function borrarLocal() { if (!confirm("Esto borrará tus datos guardados en este navegador. No se puede deshacer.")) return; localStorage.removeItem("mi_despensa_local_data"); document.cookie = "mi_despensa_local=; path=/; max-age=0; SameSite=Lax"; router.push("/auth/login"); }
  async function salirDeGrupos() { if (prompt("Escribí BORRAR para confirmar") !== "BORRAR") return; const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; await supabase.from("perfiles").update({ grupo_id: null }).eq("id", user.id); await supabase.from("user_preferences").delete().eq("user_id", user.id); await cerrarSesion(); }
  return <section className="space-y-4"><div className="surface rounded-[32px] p-6"><p className="eyebrow">Control personal</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em]">Ajustes</h1><p className="mt-2 text-tinta/60">Privacidad, preferencias y datos bajo tu control.</p></div><Card title="Cuenta"><p>Modo actual: <b>{modoLocal ? "Local" : "Cuenta con Google"}</b></p><div className="mt-3 grid gap-2"><Button variant="secondary" onClick={cerrarSesion}>Cerrar sesión</Button>{modoLocal && <Link href="/auth/login"><Button className="w-full">Entrar con Google</Button></Link>}</div></Card><Card title="Apariencia"><Select value={prefs.preferences.theme} onChange={(e) => prefs.setPreferences({ theme: e.target.value as ThemePreference })}><option value="system">Tema del sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></Select></Card><Card title="Preferencias de compra"><label className="grid gap-1 text-sm font-semibold text-tinta/65">Presupuesto base<Input type="number" value={prefs.preferences.defaultBudgetAmount ?? ""} onChange={(e) => prefs.setPreferences({ defaultBudgetAmount: Number(e.target.value) })}/></label><label className="mt-3 grid gap-1 text-sm font-semibold text-tinta/65">Frecuencia<Select value={prefs.preferences.shoppingFrequency ?? ""} onChange={(e) => prefs.setPreferences({ shoppingFrequency: e.target.value as any })}><option value="">Sin definir</option><option value="daily">Diario</option><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="monthly">Mensual</option><option value="as_needed">Cuando se necesita</option></Select></label></Card><Card title="Datos y privacidad"><p className="text-sm text-tinta/60">Usamos estos datos solo para personalizar tus listas, presupuestos y sugerencias. No vendemos datos, no usamos publicidad y no hacemos rastreo oculto.</p><div className="mt-3 grid gap-2"><Button variant="secondary" onClick={exportLocalData}>Exportar mis datos</Button>{modoLocal ? <Button variant="danger" onClick={borrarLocal}>Borrar datos locales</Button> : <Button variant="danger" onClick={salirDeGrupos}>Eliminar mis datos personales y salir de grupos</Button>}</div></Card><Card title="Proyecto open source"><p className="text-sm text-tinta/60">Mi Despensa busca ayudar, no vender datos. No usa publicidad, no incluye rastreadores ocultos y el código puede auditarse.</p><div className="mt-3 grid gap-2"><a className="font-black underline" href="https://github.com/Rodrxx-264/MiDespensa" target="_blank">Repositorio GitHub</a><Link className="font-black underline" href="/PRIVACY.md">Privacidad</Link></div></Card><Card title="Seguridad"><ul className="list-disc space-y-1 pl-5 text-sm text-tinta/65"><li>No compartas tu cuenta.</li><li>Revisa tus grupos periódicamente.</li><li>Cierra sesión si usás un dispositivo compartido.</li></ul></Card></section>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel rounded-[28px] p-5"><h2 className="text-xl font-black tracking-[-.04em]">{title}</h2><div className="mt-3">{children}</div></section>; }
