"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Input, Select } from "@/components/ui/Input";
import { CATEGORIAS, UNIDADES } from "@/lib/constants";
import { useGrupo } from "@/hooks/useGrupo";
import { usePantry } from "@/hooks/usePantry";

export default function DespensaPage() {
  const { grupo } = useGrupo(); const pantry = usePantry(grupo?.id); const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [category, setCategory] = useState("Otros"); const [unit, setUnit] = useState("unidad"); const [quantity, setQuantity] = useState(1);
  const items = pantry.items.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) || item.category?.toLowerCase().includes(query.toLowerCase()));
  return <section className="space-y-4"><div className="surface rounded-[28px] p-5"><p className="eyebrow">Inventario simple</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em]">Mi despensa</h1><p className="mt-2 text-tinta/60">Evita comprar repetido y marca lo que ya está bajo stock.</p></div><form className="panel grid gap-2 rounded-[24px] p-4" onSubmit={(e) => { e.preventDefault(); void pantry.addItem({ name, category, unit, quantity }); setName(""); }}><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Producto en casa" required/><div className="grid grid-cols-3 gap-2"><Input type="number" min="0" step="0.01" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))}/><Select value={unit} onChange={(e) => setUnit(e.target.value)}>{UNIDADES.map((u) => <option key={u}>{u}</option>)}</Select><Select value={category} onChange={(e) => setCategory(e.target.value)}>{CATEGORIAS.map((c) => <option key={c}>{c}</option>)}</Select></div><Button>Agregar a despensa</Button></form><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar en despensa"/>{items.length ? <div className="grid gap-2">{items.map((item) => <article key={item.id} className="panel rounded-[22px] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{item.name}</h2><p className="text-sm text-tinta/60">{item.quantity} {item.unit} · {item.category}</p>{item.expires_at && <p className="text-xs text-tinta/50">Vence: {item.expires_at}</p>}</div><Button variant={item.low_stock ? "primary" : "secondary"} onClick={() => pantry.updateItem(item.id, { low_stock: !item.low_stock })}>{item.low_stock ? "Bajo" : "Stock"}</Button></div><Button className="mt-2" variant="danger" onClick={() => pantry.deleteItem(item.id)}>Eliminar</Button></article>)}</div> : <p className="panel rounded-[22px] p-4 text-tinta/60">No hay productos en despensa. Agrega lo que ya tienes en casa.</p>}</section>;
}
